apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: news-app
type: Opaque
stringData:
  DB_USER: "debi"
  DB_PASSWORD: "debipass123"
  JWT_SECRET: "419461bae0350d7058bbb6629f88813c9dfd5498da471466c64caa4e14269c2b27e681f8897c6bf2664fa9bd22408cc0c0937728d13201aff27080dcf8f37d56"
